In [1]:
from backtest_port import Backtest

In [2]:
test = Backtest()

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  6 of 6 completed

In [3]:
test.return_data()

Price            Close                                                  \
Ticker            AAPL       HOOD        MSFT         NFLX        NVDA
Date
2000-01-03    0.841048        NaN   35.726719          NaN    0.089425
2000-01-04    0.770139        NaN   34.519848          NaN    0.087037
2000-01-05    0.781408        NaN   34.883835          NaN    0.084172
2000-01-06    0.713787        NaN   33.715298          NaN    0.078680
2000-01-07    0.747598        NaN   34.155903          NaN    0.079994
...                ...        ...         ...          ...         ...
2025-06-26  201.000000  84.519997  497.450012  1306.670044  155.020004
2025-06-27  201.080002  83.029999  495.940002  1323.119995  157.750000
2025-06-30  205.169998  93.629997  497.410004  1339.130005  157.990005
2025-07-01  207.820007  92.330002  492.049988  1293.599976  153.300003
2025-07-02  212.440002  97.980003  491.089996  1284.859985  157.250000

Price                         High                                       ...  \
Ticker            SPOT        AAPL        HOOD        MSFT         NFLX  ...
Date                                                                     ...
2000-01-03         NaN    0.845274         NaN   36.358881          NaN  ...
2000-01-04         NaN    0.831186         NaN   35.899109          NaN  ...
2000-01-05         NaN    0.830716         NaN   35.669248          NaN  ...
2000-01-06         NaN    0.803949         NaN   34.902996          NaN  ...
2000-01-07         NaN    0.758869         NaN   34.404936          NaN  ...
...                ...         ...         ...         ...          ...  ...
2025-06-26  775.900024  202.639999   84.800003  498.040009  1307.339966  ...
2025-06-27  772.599976  203.220001   84.879997  499.299988  1331.349976  ...
2025-06-30  767.340027  207.389999   94.239998  500.760010  1341.150024  ...
2025-07-01  722.349976  210.190002   99.180000  498.049988  1338.770020  ...
2025-07-02  709.500000  213.339996  100.879997  493.500000  1299.949951  ...

Price             Open                                          Volume  \
Ticker            MSFT         NFLX        NVDA        SPOT       AAPL
Date
2000-01-03   35.975752          NaN    0.090261         NaN  535796800
2000-01-04   34.807194          NaN    0.087873         NaN  512377600
2000-01-05   34.060109          NaN    0.084531         NaN  778321600
2000-01-06   34.385772          NaN    0.084172         NaN  767972800
2000-01-07   33.293864          NaN    0.078322         NaN  460734400
...                ...          ...         ...         ...        ...
2025-06-26  492.980011  1280.000000  155.979996  744.580017   50799100
2025-06-27  497.549988  1306.880005  156.039993  780.299988   73188600
2025-06-30  497.040009  1331.000000  158.399994  776.989990   91912800
2025-07-01  496.470001  1338.229980  156.289993  766.929993   78788900
2025-07-02  489.989990  1296.959961  152.979996  725.000000   67941800

Price
Ticker             HOOD      MSFT       NFLX       NVDA       SPOT
Date
2000-01-03          NaN  53228400        NaN  300912000        NaN
2000-01-04          NaN  54119000        NaN  300480000        NaN
2000-01-05          NaN  64059600        NaN  188352000        NaN
2000-01-06          NaN  54976600        NaN  120480000        NaN
2000-01-07          NaN  62013600        NaN   71184000        NaN
...                 ...       ...        ...        ...        ...
2025-06-26   25222500.0  21578900  2605900.0  198145700  2555300.0
2025-06-27   37005900.0  34539200  4070900.0  263234500  2793900.0
2025-06-30  101945000.0  28369000  3282900.0  194580300  1933300.0
2025-07-01  121171500.0  19945400  4993600.0  213143600  2725700.0
2025-07-02  112489000.0  16319600  3048800.0  171224100  2786300.0

[6413 rows x 30 columns]